version: "3"
services:

  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    container_name: 'docker_redis'

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="password"
    networks:
      - result-tier
      - back-tier
    container_name: 'docker_db'
  
  poll:
    build: ./poll
    restart: always
    environment:
      FLASK_DEV: dev
    ports:
      - "5000:80"
    networks:
      - poll-tier
    container_name: 'docker_poll'

  result:
    build: ./result
    restart: always
    environment:
      NODE_DEV: dev
    ports:
      - "5001:80"
    networks:
      - result-tier
    container_name: 'docker_result'
  
  worker:
    build: ./worker
    restart: always
    environment:
      JAVA_DEV: dev
    networks:
      - back-tier
    container_name: 'docker_worker'

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: