# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:

    prefix: '%env(APP_ENV)%_'
    indices:
        - name: article
          class: App\Entity\Article
          enable_serializer_groups: true