---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Updating apt cache
    apt:
      update_cache: yes

- hosts: server01_redis
  become: yes
  become_method: sudo

  tasks:
  - name: Install Redis
    apt:
      name: ['redis-server']
      state: present

- hosts: server02_postgres
  become: yes
  become_method: sudo

  tasks:
  - name: Install PostgreSQL
    apt:
      name: ['postgresql', 'libpq-dev', 'python-psycopg2']

- hosts: server03_poll
  become: yes
  become_method: sudo

  tasks:
  - name: Install Python
    apt:
      name: ['python3', 'python3-pip', 'python3-dev']
      state: present

  - name: Install uwsgi through pip3
    pip:
      name: uwsgi
      executable: pip3

- hosts: server04_result
  become: yes
  become_method: sudo

  tasks:
  - name: Install npm and nodejs
    apt:
      name: ['npm', 'nodejs']

- hosts: server05_worker
  become: yes
  become_method: sudo

  tasks:
  - name: Install Java
    apt:
      name: ['openjdk-11-jdk', 'maven']
